In [2]:
import pandas as pd

In [3]:
freq_feat = pd.read_csv('Train Data/Train Data Zip/frequency_domain_features_train.csv', delimiter=' *, *', engine='python')
heartrate_feat = pd.read_csv('Train Data/Train Data Zip/heart_rate_non_linear_features_train.csv', delimiter=' *, *', engine='python')
time_feat = pd.read_csv('Train Data/Train Data Zip/time_domain_features_train.csv', delimiter=' *, *', engine='python')

In [4]:
freq_feat.head()

,uuid,VLF,VLF_PCT,LF,LF_PCT,LF_NU,HF,HF_PCT,HF_NU,TP,LF_HF,HF_LF
0,89df2855-56eb-4706-a23b-b39363dd605a,2661.894136,72.203287,1009.249419,27.375666,98.485263,15.522603,0.421047,1.514737,3686.666157,65.018055,0.015380
1,80c795e4-aa56-4cc0-939c-19634b89cbb2,2314.265450,76.975728,690.113275,22.954139,99.695397,2.108525,0.070133,0.304603,3006.487251,327.296635,0.003055
2,c2d5d102-967c-487d-88f2-8b005a449f3e,1373.887112,51.152225,1298.222619,48.335104,98.950472,13.769729,0.512671,1.049528,2685.879461,94.280910,0.010607
3,37eabc44-1349-4040-8896-0d113ad4811f,2410.357408,70.180308,1005.981659,29.290305,98.224706,18.181913,0.529387,1.775294,3434.520980,55.328701,0.018074
4,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,1151.177330,43.918366,1421.782051,54.242160,96.720007,48.215822,1.839473,3.279993,2621.175204,29.487873,0.033912

In [5]:
heartrate_feat.head()

,uuid,SD1,SD2,sampen,higuci,datasetId,condition
0,89df2855-56eb-4706-a23b-b39363dd605a,11.001565,199.061782,2.139754,1.163485,2,no stress
1,80c795e4-aa56-4cc0-939c-19634b89cbb2,9.170129,114.634458,2.174499,1.084711,2,interruption
2,c2d5d102-967c-487d-88f2-8b005a449f3e,11.533417,118.939253,2.135350,1.176315,2,interruption
3,37eabc44-1349-4040-8896-0d113ad4811f,11.119476,127.318597,2.178341,1.179688,2,no stress
4,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,13.590641,87.718281,2.221121,1.249612,2,no stress

In [6]:
time_feat.head()

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,KURT,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_REL_RR,RMSSD_REL_RR,SDSD_REL_RR,SDRR_RMSSD_REL_RR,KURT_REL_RR,SKEW_REL_RR,uuid
0,885.157845,853.763730,140.972741,15.554505,15.553371,9.063146,69.499952,11.133333,0.533333,-0.856554,0.335218,-0.000203,-0.000179,0.017080,0.007969,0.007969,2.143342,-0.856554,0.335218,89df2855-56eb-4706-a23b-b39363dd605a
1,939.425371,948.357865,81.317742,12.964439,12.964195,6.272369,64.363150,5.600000,0.000000,-0.408190,-0.155286,-0.000059,0.000611,0.013978,0.004769,0.004769,2.930855,-0.408190,-0.155286,80c795e4-aa56-4cc0-939c-19634b89cbb2
2,898.186047,907.006860,84.497236,16.305279,16.305274,5.182201,67.450066,13.066667,0.200000,0.351789,-0.656813,-0.000011,-0.000263,0.018539,0.008716,0.008716,2.127053,0.351789,-0.656813,c2d5d102-967c-487d-88f2-8b005a449f3e
3,881.757865,893.460030,90.370537,15.720468,15.720068,5.748591,68.809562,11.800000,0.133333,-0.504947,-0.386138,0.000112,0.000494,0.017761,0.008660,0.008660,2.050988,-0.504947,-0.386138,37eabc44-1349-4040-8896-0d113ad4811f
4,809.625331,811.184865,62.766242,19.213819,19.213657,3.266724,74.565728,20.200000,0.200000,-0.548408,-0.154252,-0.000100,-0.002736,0.023715,0.013055,0.013055,1.816544,-0.548408,-0.154252,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7

In [7]:
print('Shape of frequency_domain_features : ', freq_feat.shape)
print('Shape of heart_rate_non_linear_features : ', heartrate_feat.shape)
print('Shape of time_domain_features : ', time_feat.shape)

Shape of frequency_domain_features :  (369289, 12)
Shape of heart_rate_non_linear_features :  (369289, 7)
Shape of time_domain_features :  (369289, 20)

In [8]:
Data = freq_feat.merge(heartrate_feat, on='uuid', how='inner', suffixes=('_1', '_2'))
Data = Data.merge(time_feat, on='uuid', how='inner', suffixes=('_1', '_2'))
Data.head()

,uuid,VLF,VLF_PCT,LF,LF_PCT,LF_NU,HF,HF_PCT,HF_NU,TP,...,KURT,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_REL_RR,RMSSD_REL_RR,SDSD_REL_RR,SDRR_RMSSD_REL_RR,KURT_REL_RR,SKEW_REL_RR
0,89df2855-56eb-4706-a23b-b39363dd605a,2661.894136,72.203287,1009.249419,27.375666,98.485263,15.522603,0.421047,1.514737,3686.666157,...,-0.856554,0.335218,-0.000203,-0.000179,0.017080,0.007969,0.007969,2.143342,-0.856554,0.335218
1,80c795e4-aa56-4cc0-939c-19634b89cbb2,2314.265450,76.975728,690.113275,22.954139,99.695397,2.108525,0.070133,0.304603,3006.487251,...,-0.408190,-0.155286,-0.000059,0.000611,0.013978,0.004769,0.004769,2.930855,-0.408190,-0.155286
2,c2d5d102-967c-487d-88f2-8b005a449f3e,1373.887112,51.152225,1298.222619,48.335104,98.950472,13.769729,0.512671,1.049528,2685.879461,...,0.351789,-0.656813,-0.000011,-0.000263,0.018539,0.008716,0.008716,2.127053,0.351789,-0.656813
3,37eabc44-1349-4040-8896-0d113ad4811f,2410.357408,70.180308,1005.981659,29.290305,98.224706,18.181913,0.529387,1.775294,3434.520980,...,-0.504947,-0.386138,0.000112,0.000494,0.017761,0.008660,0.008660,2.050988,-0.504947,-0.386138
4,aa777a6a-7aa3-4f6e-aced-70f8691dd2b7,1151.177330,43.918366,1421.782051,54.242160,96.720007,48.215822,1.839473,3.279993,2621.175204,...,-0.548408,-0.154252,-0.000100,-0.002736,0.023715,0.013055,0.013055,1.816544,-0.548408,-0.154252

In [9]:
Data.shape

(369289, 37)

In [10]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 369289 entries, 0 to 369288
Data columns (total 37 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   uuid               369289 non-null  object
 1   VLF                369289 non-null  float64
 2   VLF_PCT            369289 non-null  float64
 3   LF                 369289 non-null  float64
 4   LF_PCT             369289 non-null  float64
 5   LF_NU              369289 non-null  float64
 6   HF                 369289 non-null  float64
 7   HF_PCT             369289 non-null  float64
 8   HF_NU              369289 non-null  float64
 9   TP                 369289 non-null  float64
 10  LF_HF              369289 non-null  float64
 11  HF_LF              369289 non-null  float64
 12  SD1                369289 non-null  float64
 13  SD2                369289 non-null  float64
 14  sampen             369289 non-null  float64
 15  higuci             369289 non-null  float64
 16  datasetId          369289 non-null  int64
 17  condition          369289 non-null  object
 18  MEAN_RR            369289 non-null  float64
 19  MEDIAN_RR          369289 non-null  float64
 20  SDRR               369289 non-null  float64
 21  RMSSD              369289 non-null  float64
 22  SDSD               369289 non-null  float64
 23  SDRR_RMSSD         369289 non-null  float64
 24  HR                 369289 non-null  float64
 25  pNN25              369289 non-null  float64
 26  pNN50              369289 non-null  float64
 27  KURT               369289 non-null  float64
 28  SKEW               369289 non-null  float64
 29  MEAN_REL_RR        369289 non-null  float64
 30  MEDIAN_REL_RR      369289 non-null  float64
 31  SDRR_REL_RR        369289 non-null  float64
 32  RMSSD_REL_RR       369289 non-null  float64
 33  SDSD_REL_RR        369289 non-null  float64
 34  SDRR_RMSSD_REL_RR  369289 non-null  float64
 35  KURT_REL_RR        369289 non-null  float64
 36  SKEW_REL_RR        369289 non-null  float64
dtypes: float64(34), int64(1), object(2)
memory usage: 107.1+ MB

In [11]:
Data[['HR','condition']]

               HR     condition
0       69.499952     no stress
1       64.363150  interruption
2       67.450066  interruption
3       68.809562     no stress
4       74.565728     no stress
...           ...           ...
369284  83.384647     no stress
369285  61.314243     no stress
369286  59.028594     no stress
369287  75.978628     no stress
369288  74.197905     no stress

[369289 rows x 2 columns]

In [12]:
Data.columns

Index(['uuid', 'VLF', 'VLF_PCT', 'LF', 'LF_PCT', 'LF_NU', 'HF', 'HF_PCT',
       'HF_NU', 'TP', 'LF_HF', 'HF_LF', 'SD1', 'SD2', 'sampen', 'higuci',
       'datasetId', 'condition', 'MEAN_RR', 'MEDIAN_RR', 'SDRR', 'RMSSD',
       'SDSD', 'SDRR_RMSSD', 'HR', 'pNN25', 'pNN50', 'KURT', 'SKEW',
       'MEAN_REL_RR', 'MEDIAN_REL_RR', 'SDRR_REL_RR', 'RMSSD_REL_RR',
       'SDSD_REL_RR', 'SDRR_RMSSD_REL_RR', 'KURT_REL_RR', 'SKEW_REL_RR'],
      dtype='object')

In [13]:
column_names = list(Data.columns.values)
column_names

['uuid',
 'VLF',
 'VLF_PCT',
 'LF',
 'LF_PCT',
 'LF_NU',
 'HF',
 'HF_PCT',
 'HF_NU',
 'TP',
 'LF_HF',
 'HF_LF',
 'SD1',
 'SD2',
 'sampen',
 'higuci',
 'datasetId',
 'condition',
 'MEAN_RR',
 'MEDIAN_RR',
 'SDRR',
 'RMSSD',
 'SDSD',
 'SDRR_RMSSD',
 'HR',
 'pNN25',
 'pNN50',
 'KURT',
 'SKEW',
 'MEAN_REL_RR',
 'MEDIAN_REL_RR',
 'SDRR_REL_RR',
 'RMSSD_REL_RR',
 'SDSD_REL_RR',
 'SDRR_RMSSD_REL_RR',
 'KURT_REL_RR',
 'SKEW_REL_RR']

In [15]:
revised_columns = [ elem for elem in column_names if elem not in ['uuid','condition','HR']] #column_names.remove('uuid','condition','HR')
revised_columns

['VLF',
 'VLF_PCT',
 'LF',
 'LF_PCT',
 'LF_NU',
 'HF',
 'HF_PCT',
 'HF_NU',
 'TP',
 'LF_HF',
 'HF_LF',
 'SD1',
 'SD2',
 'sampen',
 'higuci',
 'datasetId',
 'MEAN_RR',
 'MEDIAN_RR',
 'SDRR',
 'RMSSD',
 'SDSD',
 'SDRR_RMSSD',
 'pNN25',
 'pNN50',
 'KURT',
 'SKEW',
 'MEAN_REL_RR',
 'MEDIAN_REL_RR',
 'SDRR_REL_RR',
 'RMSSD_REL_RR',
 'SDSD_REL_RR',
 'SDRR_RMSSD_REL_RR',
 'KURT_REL_RR',
 'SKEW_REL_RR']

In [18]:
len(revised_columns)

34

In [23]:
kailas = revised_columns[:11]
kailas

['VLF',
 'VLF_PCT',
 'LF',
 'LF_PCT',
 'LF_NU',
 'HF',
 'HF_PCT',
 'HF_NU',
 'TP',
 'LF_HF',
 'HF_LF']

In [24]:
len(kailas)

11

In [25]:
nidhi = revised_columns[11:22]
nidhi

['SD1',
 'SD2',
 'sampen',
 'higuci',
 'datasetId',
 'MEAN_RR',
 'MEDIAN_RR',
 'SDRR',
 'RMSSD',
 'SDSD',
 'SDRR_RMSSD']

In [26]:
len(nidhi)

11

In [27]:
devi = revised_columns[22:]
devi

['pNN25',
 'pNN50',
 'KURT',
 'SKEW',
 'MEAN_REL_RR',
 'MEDIAN_REL_RR',
 'SDRR_REL_RR',
 'RMSSD_REL_RR',
 'SDSD_REL_RR',
 'SDRR_RMSSD_REL_RR',
 'KURT_REL_RR',
 'SKEW_REL_RR']

In [28]:
len(devi)

12